

name: Acme group Bstack Automate tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.11'
          distribution: 'adopt'

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: 'BUILD_INFO'
          project-name: 'REPO_NAME'

      - name: Run test
        run: |
          rm -f -- browserstack.yml
          ln src/test/resources/conf/capabilities/browserstack-parallel-devices.yml browserstack.yml
          mvn clean test -P bstack-parallel-devices


