

name: Acme group Bstack Automate tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: BrowserStack Env Setup
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: 'BUILD_INFO'
          project-name: 'REPO_NAME'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '16.0.1'
          distribution: 'adopt'
          cache: 'maven'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Percy
        run: npm install @percy/cli

      - name: Run test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: |
          rm -f -- browserstack.yml
          ln src/test/resources/conf/capabilities/browserstack-parallel-browsers.yml browserstack.yml
          npx percy exec -- mvn clean test -P bstack-parallel

